### ISSUE TITLE
Core Organizer Functionality

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#14]
## Story/Task Details
- [x] Create/Edit Tournament Endpoints - Backend
- [x] User Interface for managing Tournaments
- [x] Finalize linting and unit testing convention for the backend

### User Story: As an organizer, I want to create a new tournament so that I can have people join the tournament.
Scenario 1: An organizer wants to create a new tournament.
- Given: the organizer is on the create new tournament page;
- When: the tournament details are entered and the create tournament button is pressed;
- Then: this tournament is added to the list of tournaments;
Scenario 2: An organizer changes his/her mind about creating a new tournament.
- Given: the organizer is on the  create new tournament page;
- When: the cancel button is pressed;
- Then: the tournament is not added to the list of tournaments and they are returned to the home page.
### User Story: As an organizer, I want to manage the tournament so that I can update the bracket and/or details.
Scenario 1: An organizer wants to manage a tournament.
- Given: the organizer is on the tournament page;
- When: the detail fields are changed and the update button is pressed;
- Then: the tournament bracket and/or details are updated;
### User Story: As an organizer, I want to delete a tournament so that I can cancel a tournament.
Scenario 1: An organizer wants to delete an existing tournament.
- Given: the organizer is on the tournament page;
- When: the delete tournament button is pressed;
- Then: the tournament is removed from the list of tournaments;
### User Story: As an organizer, I want to add matches to a tournament manually.
Scenario 1: An organizer wants to add a match to a tournament.
Given the organizer is on the tournament page;
When the add match button pressed and all details for the match are entered;
Then the match is added to the tournament.
### User Story: As an organizer, I want to delete a match manually.
Scenario 1: An organizer wants to delete a match from a tournament.
Given the organizer is on the tournament matches page;
When the delete match button is pressed for a match;
Then the match is removed from the tournament.
### User Story: As an organizer, I want to edit a match manually.
Scenario 1: An organizer wants to edit a match in a tournament.
Given the organizer is on the tournament matches page;
When the edit match button is pressed for a match;
Then an interface pops up allowing the organizer to edit matches.
### User Story: As an organizer, I want to publish a match manually.
Scenario 1: An organizer wants to publish a match for a tournament.
Given the organizer is on the tournament matches page;
When the publish  match button is pressed for a match;
Then the match now can be viewed by people other than the organizer.

## Done Done Criteria
Frontend and Backend unit tests are successful
