### ISSUE TITLE
Create Basic Authentication Application

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#2]
## Story/Task Details
- [ ] ExpressJS Server
- [ ] Configure to work with React
- [ ] Implement Authentication UI
- - [ ] Registration
- - [ ] Login
- [ ] Implement Authentication Backend
- - [ ] Registration
- - [ ] Login

## Acceptance Scenarios
- Given: A user is on the login page and has already registered
- When: Their email and password is entered and login button is pressed
- Then: The user is shown as authenticated and redirected to a landing page

## Done Done Criteria
When all unit testing pass.
