### ISSUE TITLE
Core Teams Functionality

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#41]
## Story/Task Details
- [x] Participant should be able to create teams
- [ ] Participants should be able to edit teams
- [ ] Participants should be able to delete teams
- [ ] Participants should be able to join/leave teams
- [ ] Participants should be able to search for teams
- [ ] Participants should be able to promote members to team captain (and replace the original team captain)
- [ ] Participants should be able to invite team members to their team

### Create Team
- Given: A user wants to create a team
- When: The user is on the teams page and clicks on the create team button
- Then: The team is created with the user as the team captain
### Edit Team
- Given: A user wants to edit a team
- When: The user is on the teams page and clicks on the edit team button for a team
- Then: The tournament form is pre-populated and the user is prompted to edit a team
### Delete Team
- Given: A user wants to delete a team
- When: The user is on the teams page and clicks on the delete team button for a team
- Then: The user is prompted to confirm the deletion and then the team is deleted
### Leave Team
- Given: A user wants to leave a team
- When: The user is on the teams page and clicks on the leave team button for a team
- Then: The user is prompted to confirm leaving the team, and then the user is withdrawn from the team
### Search Teams
- Given: A user wants search for teams
- When: The user is on the teams page and submits a team search query
- Then: The user is returned a list of teams
### Transfer Team Ownership
- Given: A user wants to transfer ownership of a team
- When: The user is on a particular team page, is the team captain, and clicks on the transfer ownership button next to another user
- Then: The user is asked for a confirmation, then the other user is promoted to the team captain while the original user is demoted
### Invite Team Member
- Given: A user wants to invite team members
- When: A user is on their team page and submits an email of another user to invite on the platform
- Then: The invitation is sent to the other user and the user is added to the team as an unconfirmed member
