### ISSUE TITLE
[EPIC] Referee Functionality

### ISSUE THREAD

**Issue by dli357** [TournamentBuzz/main#61]
## Story/Task Details
- [x] Add referees list to database model
- [x] Allow referees to edit match results (winner, score)
- [x] Allow tournament organizers to add referees to a tournament
- [x] Allow tournament organizers to remove referees from a tournament

## Acceptance Scenarios
- Given: A tournament organizer wants to add a referee to a tournament
- When: The tournament organizer is on the referees page and submits an email of a person
- Then: The person (if valid) is added as a referee to the tournament (ensure person exists and not currently in the tournament).

- Given: A tournament organizer wants to remove a referee from a tournament
- When: The tournament organizer is on the referees page and removes an email of a person
- Then: The person is removed as a referee from the tournament.

- Given: A tournament organizer wants to add a referee to a tournament
- When: The tournament organizer is on the add referees page and submits an email of a person
- Then: The person (if valid) is added as a referee to the tournament (ensure person exists and not currently in the tournament).

- Given: A referee wants to submit scores for a match
- When: A user is on the match page of a tournament they are a referee for and clicks on the submit scores button
- Then: The referee is shown a screen to allow them to submit scores. (Acts as editing a match)

## Done Done Criteria
Passing unit tests
